// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARhlG2-dqM06pAFCLCG0GrBKcdv1gMgVo',
    appId: '1:301273450763:web:ec1af352bb219bfc827a0e',
    messagingSenderId: '301273450763',
    projectId: 'digital-inventory-e58a8',
    authDomain: 'digital-inventory-e58a8.firebaseapp.com',
    storageBucket: 'digital-inventory-e58a8.firebasestorage.app',
    measurementId: 'G-HZ2FB4QQWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirX1kjh0sxZk0jFGl5SHjBMG9rEVCw4o',
    appId: '1:301273450763:android:7dd0d80d7633e2e1827a0e',
    messagingSenderId: '301273450763',
    projectId: 'digital-inventory-e58a8',
    storageBucket: 'digital-inventory-e58a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmnjW1SL_AJwsKoqt25Mc7NcFeopYs7E',
    appId: '1:301273450763:ios:a6f60c182a7887cd827a0e',
    messagingSenderId: '301273450763',
    projectId: 'digital-inventory-e58a8',
    storageBucket: 'digital-inventory-e58a8.firebasestorage.app',
    iosBundleId: 'com.example.digitalInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmnjW1SL_AJwsKoqt25Mc7NcFeopYs7E',
    appId: '1:301273450763:ios:a6f60c182a7887cd827a0e',
    messagingSenderId: '301273450763',
    projectId: 'digital-inventory-e58a8',
    storageBucket: 'digital-inventory-e58a8.firebasestorage.app',
    iosBundleId: 'com.example.digitalInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARhlG2-dqM06pAFCLCG0GrBKcdv1gMgVo',
    appId: '1:301273450763:web:a021ebdd0731abcd827a0e',
    messagingSenderId: '301273450763',
    projectId: 'digital-inventory-e58a8',
    authDomain: 'digital-inventory-e58a8.firebaseapp.com',
    storageBucket: 'digital-inventory-e58a8.firebasestorage.app',
    measurementId: 'G-JTZT4V3NT5',
  );
}
