// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:digital_inventory/models/local_asset.dart';
import 'package:digital_inventory/models/local_document.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DocumentSyncStatusAdapter());
    registerAdapter(LocalAssetAdapter());
    registerAdapter(LocalDocumentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DocumentSyncStatusAdapter());
    registerAdapter(LocalAssetAdapter());
    registerAdapter(LocalDocumentAdapter());
  }
}
